name: Pre-Commit

on:
 push:
 workflow_dispatch:

env:
  TERRAFORM_DOCS_VERSION: v0.16.0
  TFLINT_VERSION: v0.44.1
  
jobs:
   preCommitMaxVersion:
       name: Max TF pre-commit
       runs-on: ubuntu-latest
       needs: collectInputs
       steps:
         - name: Checkout
           uses: actions/checkout@v3
           with:
             ref: ${{ github.event.pull_request.head.ref }}
             repository: ${{github.event.pull_request.head.repo.full_name}}
             
         - name: view
           run: |
             echo "${{ github.event.pull_request.head.ref }}"
             echo "${{github.event.pull_request.head.repo.full_name}}"
   
         - name: Terraform min/max versions
           id: minMax
           uses: clowdhaus/terraform-min-max@v1.2.4
   
         - name: Pre-commit Terraform ${{ steps.minMax.outputs.maxVersion }}
           uses: clowdhaus/terraform-composite-actions/pre-commit@v1.8.3
           with:
             terraform-version: ${{ steps.minMax.outputs.maxVersion }}
             tflint-version: ${{ env.TFLINT_VERSION }}
             terraform-docs-version: ${{ env.TERRAFORM_DOCS_VERSION }}
             #install-hcledit: true