name: Pre-Commit Max Version

on:
 #push:
 workflow_dispatch:

env:
  TERRAFORM_DOCS_VERSION: v0.16.0
  TFLINT_VERSION: v0.44.1
  
jobs:
   collectInputs:
     name: Collect workflow inputs
     runs-on: ubuntu-latest
     outputs:
       directories: ${{ steps.dirs.outputs.directories }}
     steps:
      - name: Checkout
        uses: actions/checkout@v3
      # output: [".", "./examples/ec2-instance"]
      - name: Get root directories
        id: dirs
        uses: clowdhaus/terraform-composite-actions/directories@v1.8.3
   preCommitMaxVersion:
       name: Max TF pre-commit
       runs-on: ubuntu-latest
       needs: collectInputs
       steps:
         - name: Checkout
           uses: actions/checkout@v3
         #  with:           # As it is pre-commit, that is why before mergging we should check everything on PR repo and branch.
         #     ref: ${{ github.event.pull_request.head.ref }}  # PR - source branch
         #     repository: ${{github.event.pull_request.head.repo.full_name}}  # PR - repo
             
         - name: view
           run: |
             echo "${{ github.ref_name }}"
             echo "${{ github.repository }}"
   
         - name: Terraform min/max versions
           id: minMax
           uses: clowdhaus/terraform-min-max@v1.2.4
   
         - name: Pre-commit Terraform ${{ steps.minMax.outputs.maxVersion }}
           uses: clowdhaus/terraform-composite-actions/pre-commit@v1.8.3
           with:
             terraform-version: ${{ steps.minMax.outputs.maxVersion }}
             tflint-version: ${{ env.TFLINT_VERSION }}
             terraform-docs-version: ${{ env.TERRAFORM_DOCS_VERSION }}
             install-hcledit: true
             #args: '--files $(ls *.tf)'
                  