name: Generate terraform docs
on:
  pull_request:
  push:
   branches:
   - main
  workflow_dispatch:
  
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main

    - name: Render terraform docs inside the DOCS.md and push changes
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: .
        output-file: "DOCS.md"
        output-method: inject
        git-push: "true"
   
